spring:
  profiles:
    active: prod
  application:
    name: telegram-dnd-bot
  datasource:
    url: jdbc:h2:file:./db/bot
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
bot:
  path: ""
  username: FiveXGameBot