all:
  children:
    springbox_server_1:
      hosts:
        location_server_1:
          ansible_host: 45.142.44.202
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible
    service:
      children:
        springbox_server_1: {}
    db:
      children:
        springbox_server_1: {}