name: Deploy Containers
on:
  release:
    types:
      - created
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - run: mvn --batch-mode -Drevision=${GITHUB_REF##*/} clean package
      - uses: actions/upload-artifact@v4
        with:
          name: telegram-dnd-bot.jar
          path: target/telegram-dnd-bot.jar
  Deploy:
    runs-on: ubuntu-latest
    environment: springbox
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install ansible
      - name: set ansible config secrets
        env:
          ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
          ANSIBLE_VAULT_KEY: ${{ secrets.ANSIBLE_VAULT_KEY }}
        run: |
          mkdir .ssh
          echo "$ANSIBLE_SSH_KEY" > ~/.ssh/ansible
          chmod 600 .ssh/ansible
          echo "$ANSIBLE_VAULT_KEY" > .ansible_vault_key
          chmod 600 .ansible_vault_key
      - uses: actions/download-artifact@v4
        with:
          name: telegram-dnd-bot.jar
          path: ansible/roles/service/files/
      - run: ansible-playbook ansible/setup_server.yml -i ansible/inventory/sprintbox.yml --vault-password-file .ansible_vault_key
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
